#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

command -v quicktype >/dev/null 2>&1 || {
  echo "gen-ipc.sh: 'quicktype' not found in PATH. Install with: brew install quicktype" >&2
  exit 1
}

mkdir -p DSPlay/Generated

quicktype \
  --src-lang typescript \
  --lang swift \
  --top-level "DSPlayIPC" \
  --just-types \
  --swift-5-support \
  --acronym-style original \
  --density normal \
  --src shared/ipc-schema.ts \
  --out DSPlay/Generated/IPCTypes.swift.tmp

# Add a generated-file banner
{
  echo "// AUTO-GENERATED by scripts/gen-ipc.sh from shared/ipc-schema.ts"
  echo "// Do not edit by hand. Re-run \`scripts/gen-ipc.sh\` after changing the schema."
  echo ""
  cat DSPlay/Generated/IPCTypes.swift.tmp
} > DSPlay/Generated/IPCTypes.swift

rm DSPlay/Generated/IPCTypes.swift.tmp
echo "gen-ipc.sh: wrote DSPlay/Generated/IPCTypes.swift"
